### ISSUE TITLE
could you help a node novice?

### ISSUE THREAD

**Issue by rickdog** [dominictarr/hyperscript#32]
I'm trying to learn hyperscript from your examples/index.html.
After I download the gist, how do I get the example to work?
There are errors when I load examples/index.html in the browser:
```
ReferenceError: require is not defined index.js:1:4
TypeError: h is not a function index.html:15:0
```
your help would be greatly appreciated in getting me over this startup hump

**Comment by dominictarr** [comment]
ah, I think that should be deleted, use the `index.html` in the root of the project instead.
