### ISSUE TITLE
Should throw when omitting comma that separates arguments

### ISSUE THREAD

**Issue by mattijsbliek** [dominictarr/hyperscript#45]
When omitting the comma after the attributes object in the example below, I would expect Hyperscript to throw an error. Right now I just get back an empty `<a></a>` element, which makes it hard to track down what went wrong.

```h('a', { href: '#' } [
	h('h1', 'title')
])```

**Comment by dominictarr** [comment]
unfortunately that is just a javascript syntax quirk. without the comma the js parser thinks those `[]` are a property access on the `{}`. non of my code even gets called when that happens so there is no way hyperscript can know that has happened. It would probably be better if array syntax and dynamic property access did not use the same characters.

**Comment by mattijsbliek** [comment]
Right I see, that's unfortunate indeed. Thanks for the swift reply anyways :)
