### ISSUE TITLE
AMD / UMD support?

### ISSUE THREAD

**Issue by iFarmGolems** [dominictarr/hyperscript#57]
I would love to use this in a browser!

**Comment by dominictarr** [comment]
just use browserify ;)

**Comment by georgir** [comment]
There are a lot of contexts where "just use browserify" is not a suitable answer. Having a pre-built version available directly from a popular public CDN will greatly increase the popularity and usability of the package, i.e. for bookmarklets, greasemonkey userscripts, code sample sites like jsfiddle or jsbin etc.
