### ISSUE TITLE
Recommendations for dynamic classes

### ISSUE THREAD

**Issue by twolfson** [dominictarr/hyperscript#59]
I'm trying out `hyperscript` but can't seem to find any documentation on what the preferred way to handle dynamic classes. I tried using Jade/Pug's syntax (i.e. `div.class1(class={class2: true})`) but `hyperscript` doesn't seem to respect that:

```js
// Load in our dependencies
var h = require('hyperscript');

// Generate our element with both class attributes and `className` property
console.log(h('div.class1', {className: 'class2'}));
// Expected: <div class="class1 class2">
// Actual: <div class="class2">
```

I know there are options like `classnames` but it seems tedious like it will be an annoying maintenance tax to transition all classes from `.` syntax to `classnames` whenever a dynamic class is added. Something like the example above would be ideal:

```js
console.log(h('div.class1', {
  className: classnames({'class2': true})
}));
// <div class="class1 class2">
```

**Comment by dominictarr** [comment]
hmm, can you describe what you are using this for, and how you want to use it?
is it one class that is passed in at the time you create the object, or is it a class that changes dynamically?

if the first, i would probably just do `h('div.'+classNames)` ugly, but simple, i guess if you did this lots, you'd want a pattern.

It might be simpler if attributes allowed arrays, but just called `.join(' ')` on them.,

**Comment by twolfson** [comment]
I'm using this as a templating language for a browser based application. Currently, the goal is to do class based OOP for components (i.e. render content once, update components via imperative JS) with the possibility of switching to declarative render (i.e. render/update content declaratively via virtual DOM).

In both scenarios, the result is create an element once -- the dynamic part is mostly during the template itself. To elaborate, the class for the element changes based on the parameters the component received. A simple example would be a collapse/expand component which initializes either collapsed or expanded:

```js
// If collapsed
h('div.collapse');

// If expanded
h('div.collapse.collapse--expanded');
```

To do this in the same line of code, it would be (which you suggested above):

```js
h('div.collapse' + (isCollapsed ? '' : '.collapse-expanded'));
```

However, that gets quite large quite fast if there are multiple dynamic classes (haven't reached that point yet).

Would it be possible to do the following:

- Create element first
- Set attributes
- Set id/add classes

`classList` seems to support `.add()` instead of directly overwriting so it should work. The current implementation seems to do:

- Create element first
- Set id/add classes
- Set attributes

which causes attributes to overwrite classes =/

**Comment by dominictarr** [comment]
What about using an observable for the className?
you may want to checkout https://github.com/mmckegg/mutant

**Comment by dominictarr** [comment]
if you set the class then you set it again, how does hyperscript know you meant to add classes, and not replace them? I think you need to set all the classes for this to really make sense.

**Comment by twolfson** [comment]
I don't follow the suggestion for `className` =/ I'm using this as a template function -- there's no dynamic alteration of class name via `hyperscript`. It's that it's the same function but receiving different parameters so it generates different classes.

My reference to "Create element first" etc was about the `hyperscript` code itself, not how I attach to it

**Comment by dominictarr** [comment]
so you want to write a function that creates an element that sets a basic class name, plus another class that you pass in as an argument?

**Comment by twolfson** [comment]
With respect to `hyperscript` knowing intent of concatenating or replacing classes, I think it's a subjective choice for the library. The current implementation does replacement but it could almost as easily do concatenation.

I think concatenation feels more intuitive because this is a one-time generation. The current setup might exist solely due to not thinking of the use case and be a non-issue for when releasing a new version

**Comment by twolfson** [comment]
I would like the syntax:

```js
h('div.class1', {
  className: 'class2'
});
```

to generate:

```js
<div class="class1 class2">
```

**Comment by twolfson** [comment]
The syntax makes more sense when used with a library like `classnames`:

```js
h('div.class1', {
  className: classnames({class2: bool})
});
// <div class="class1">
// or (based on boolean)
// <div class="class1 class2">
```

**Comment by dominictarr** [comment]
urm, I'm not really into that syntax. That would mean handling `className` specially, and that is surprising behaviour. what is wrong with `h('div.class1'+customClass)`

**Comment by twolfson** [comment]
I think it might be surprising behavior in a non-HTML sense but in the context of HTML, concatenation makes sense as you wouldn't typically declare both of them. As mentioned before, this is widely used/supported by Jade/Pug:

https://pugjs.org/language/attributes.html#class-attributes

As I mentioned, it doesn't require handling `className` specially; if we change the order of operations so we do:

1. Create element
2. Set attributes
3. Set id/add classes

then it should all work. We are using `classList.add()` not `classList.set()`:

https://github.com/dominictarr/hyperscript/blob/81914f9b54347093343d5683c5533f7fcd342967/index.js#L29-L30

My issue with `h('div.class1' + customClass)` is that it gets bulky fast with ternaries:

```js
h('div' + (true ? '.class1' : '') + (true ? '.class2' : ''));
```

We can't use a library like `classnames` in this scenario as `classnames` generates space delimited classes for the `className` attribute instead of `.` prefixes ones:

```js
classnames({class1: true, class2: true});
// "class1 class2"
// Where we need:
// ".class1.class2"
```

I suppose we could write another library or request support for `.` output in `classnames` but that's why we're having this discussion first =)

**Comment by dominictarr** [comment]
hyperscript applies rules from left to right. {} are interpreted as attributes, but it doesn't actually have to be first. `h('div', 'foo', {className: 'blah'})` works. `<div class=blah>foo</div>`

Sorry, I just don't feel that there is a good justification for this change. If anything, i think the `'div.blah'` syntax was not the best part of hyperscript anyway...

**Comment by twolfson** [comment]
Alright, cool. That answers my initial question then I guess =/

Maybe `hyperscript` should drop the `#id` and `.class` syntax and move it into a wrapper function/module which also can handle concatenation. That way you can isolate being similar to Jade/Pug flavors

For me, I think the solution is to avoid using the `.class` syntax and use `className` consistently by convention so that there is little/no maintenance tax when we need dynamic classes:

```js
h('div', {
  className: 'class1'
});
// to
h('div', {
  className: classnames('class1', {class2: bool})
});
```

Thanks for the quick responses and helpful discussion @dominictarr =)
